dist: focal
arch:
  - amd64
  - ppc64le
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12-dev"  # development branch
  - "pypy3.9-7.3.9"
jobs:
 exclude:
  - arch: ppc64le
    python: "pypy3.9-7.3.9"

allow_failures:
    - python: "3.12-dev"

install:
  - pip install coveralls tox-travis importlib_metadata
script:
  tox
after_success:
  coveralls
